# Generated by Django 4.1.1 on 2022-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
