# Generated by Django 4.1.1 on 2022-11-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0002_shoe_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='published_date',
        ),
    ]
