# Generated by Django 4.1.1 on 2022-11-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0003_remove_shoe_created_date_remove_shoe_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
