# Generated by Django 4.1.1 on 2022-11-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0004_shoe_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
