# Generated by Django 4.1.1 on 2022-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe', '0006_remove_shoe_photo_shoe_brand_alter_shoe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
